### PR TITLE
Add FreeMarker language support

### PR DESCRIPTION
**Pull request by andreblanke**
Adds support for the Apache FreeMarker template language with `.ftl`, `.ftlh`, and `.ftlx` as associated file extensions.

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Thank you for your PR! Ignore travis CI failing I'm the process of switching CI providers. Could you also add a test file to `tests/data`. You can read about how to do this in [CONTRIBUTING](https://github.com/XAMPPRocky/tokei/blob/master/CONTRIBUTING.md#tests). Once there is a test for it I would be happy to merge it in.

**Comment by andreblanke** [comment]
Sorry about the missing test file. I've added `ftl.ftl`. Should I include further test files for the `.ftlh` and `.ftlx` extensions or is one file sufficient?

**Comment by XAMPPRocky** [comment]
@andreblanke One file is sufficient however it seems the test is wrong, can you review so it passes GitHub Actions?

**Comment by XAMPPRocky** [comment]
Thank you for your PR, and congrats on your first contribution! 🎉

**Pull request merged**
