### PR TITLE
impr: Add `-R` option to modify row format

### LINKED ISSUE #895: Option to use box drawing characters for nicer output
Example: Using `─` instead of `-`, and `━` instead of `=`.

### PR DESCRIPTION
**Pull request by 5HT2**
This is my first pull request here, and my first time ever using Rust, so please let me know if I did anything wrong / something could be improved. Closes #895.

Default output (unchanged):

Box drawing option:

### CODE REVIEW

**Comment by 5HT2** [comment]
This also leaves the option open to use *different* characters, but I wasn't sure if it was desirable to also add other options. I mainly just wanted box drawing support to look nice :p

**Comment by 5HT2** [comment]
So just, replacing the original characters with box drawing?

**Comment by 5HT2** [comment]
@XAMPPRocky is this alright?

**Comment by XAMPPRocky** [comment]
Yep, LGTM! Thank you for your PR, and congrats on your first contribution! 🎉

**Pull request merged**
