### PR TITLE
Add support for smalltalk

### PR DESCRIPTION
**Pull request by jake-87**
Added support for the smalltalk programming language.

### CODE REVIEW

**Comment by jake-87** [comment]
That is definitely be a problem. Afaik, smalltalk programs almost always have two extensions on the end, such as .cs.st or .pck.st

**Comment by jake-87** [comment]
Would it be better to add both of those options as potential file extensions? E.G. `"extensions": ["cs.st", "pck.st"]`

**Comment by jake-87** [comment]
@spenserblack Should be fixed now

**Comment by spenserblack** [comment]
@jake-87 cool! I'm not a collaborator, though, so you'll probably want to ping @XAMPPRocky instead so they can run the workflows 🙂

**Comment by jake-87** [comment]
Ah, sorry about that. @XAMPPRocky, workflows should be good to go

**Comment by jake-87** [comment]
@XAMPPRocky ?

**Comment by XAMPPRocky** [comment]
Thank you for your PR, and congrats on your first contribution! 🎉

**Pull request merged**
