### PR TITLE
Update `--languages` Output Format

### PR DESCRIPTION
**Pull request by Embers-of-the-Fire**
### Update `--languages` Output Format

Now it seems like this:

```
──────────────────────────────────────────────────────────────────
| Language                           Extensions                  |
|────────────────────────────────────────────────────────────────|
| ABNF                               abnf                        |
| AWK                                awk                         |
| ABAP                               abap                        |
| ActionScript                       as                          |
| ...                                ...                         |
──────────────────────────────────────────────────────────────────
```

> `EmojiCode` is treated differently, since emojis are usually rendered as two characters, so I add a `\u+200b` to render it correctly.

### Other Small Changes

- Updated some dependencies (no side-effects afaik).
- Remove some unnecessary reference.
- Change those `expect()` into `unwrap_or_else(|| panic!())`, see [Clippy-expect_fun_call](https://rust-lang.github.io/rust-clippy/master/index.html#/expect_fun_call).

## Other Ideas

1. See #998 
2. I'm considering adding a TUI for tokei and would like to ask if it's better to integrate it as a built-in feature in this repository or create a separate forked version.

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Would you mind creating separate PRs for each of the changes rather than bundling them up? It makes it easier for me to tell what I'm accepting and quicker for me to review.

> I'm considering adding a TUI for tokei and would like to ask if it's better to integrate it as a built-in feature in this repository or create a separate forked version.

I'd say open a discussion with your ideas of what a TUI of token would do, and how it would be valuable for users, and we can discuss whether it's appropriate for this repo. Either way a fork shouldn't be needed as `tokei` is available as a library as well a binary.

**Comment by Embers-of-the-Fire** [comment]
> Thank you for your issue! Would you mind creating separate PRs for each of the changes rather than bundling them up? It makes it easier for me to tell what I'm accepting and quicker for me to review.

Actually it's because I've submitted this PR from my repo, and Github bundled all commits even if they're already merged before. I will pay attention to this issue when submitting PR in the future. Sorry for that.

**Comment by XAMPPRocky** [comment]
Could you also split up this PR?

**Comment by Embers-of-the-Fire** [comment]
> Could you also split up this PR?

Sure. See PR #1005, #1006

**Pull request closed without merging**
