### PR TITLE
Add Emojicode support

### PR DESCRIPTION
**Pull request by NieDzejkob**

### CODE REVIEW

**Comment by NieDzejkob** [comment]
Retrying CI...

**Comment by XAMPPRocky** [comment]
@NieDzejkob Thank you for PR! Yeah my CI infra seems to catch a lot of spurious errors. If it passes on one CI platform I will merge it then.

**Comment by NieDzejkob** [comment]
Oh, it's fine then - passing on AppVeyor.

**Comment by XAMPPRocky** [comment]
Thank you again for your PR, and congrats on your first contribution! 🎉

**Pull request merged**
