### PR TITLE
Add Mercury support

### PR DESCRIPTION
**Pull request by 80aff123-9163-4f3e-a93d-4a2f35af9be1**

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Thank you for your PR! Would you also be able to add a tests file under `tests/data`? Instructions of how to do can be found in the contributing or looking at other examples.

**Comment by ccao001** [comment]
@XAMPPRocky 

Hi! Thank you for letting me know.

I will add a test tomorrow.

**Comment by brightly-salty** [comment]
Hi, I'd really enjoy getting Mercury support for tokei. @80aff123-9163-4f3e-a93d-4a2f35af9be1 could you add that tests/data file, or maybe I could try adding Mercury support in a new PR if you don't feel qualified to do that?

**Comment by XAMPPRocky** [comment]
Going to close this as inactive, if you'd like to add support for this, feel free to open a new PR.

**Pull request closed without merging**
