### PR TITLE
[issue_891] give more space for Files column

### LINKED ISSUE #891: :bug: Line overflow on large quantity of code
Hi, i recently a large monolith of code, and it seems that the `go` language is overflowing by 1 character.
I found that kinda funny you i let the report here:

```apl
===============================================================================
 Language            Files        Lines         Code     Comments       Blanks
===============================================================================
 ActionScript          356        45301        29502         8428         7371
 Ada                    20         5680         3362         1120         1198
 Alex                  165        33733        33304            0          429
 Arduino C++             2          688          514          105           69
 AsciiDoc               31         2323         1642            0          681
 ASN.1                  21          956          532          225          199
 ASP.NET              2667        94327        82288         2994         9045
 Assembly             1694       859710       745771        49839        64100
 GNU Style Assembly  22740      2686852      2125776       251771       309305
 Autoconf             3288       370382       263411        52102        54869
 Automake              889        50159        39011         3929         7219
 BASH                 2907       142865       104729        20373        17763
 Batch                 985        30684        23404         1084         6196
 C                   29345     15123070     11521828      1996217      1605025
 C Header            98922     20750489     10228588      7688731      2833170
 CMake               20943      1207931       801891       245869       160171
 C#                  24998      6421668      4990414       621639       809615
 C Shell                 9          316          178           54           84
 Clojure                91        20660        17838         1057         1765
 CoffeeScript          403        28983        21333         3215         4435
 Coq                    29          284          276            0            8
 C++                 73098     14877486     11431924      1368861      2076701
 C++ Header          22619      4644829      3246269       745174       653386
 CSS                  5446      3466679      3005878        80209       380592
 D                     254         6304         5476          349          479
 Dart                    2          117           93            7           17
 Dockerfile           2801        71710        45326        12073        14311
 .NET Resource         254        61951        47906        13989           56
 Dust.js                 1           17           16            0            1
 Emacs Lisp             36         7554         5077         1567          910
 Elixir               1541       171180       147859         5730        17591
 Erlang                175        39728        26639         8961         4128
 F#                      5           61           43            1           17
 Fish                    8          988          688          153          147
 FlatBuffers Schema     19         2603         2078           70          455
 FORTRAN Legacy        180        13199         5241         7763          195
 FORTRAN Modern        133         2802         2524           78          200
 GDB Script              1           71           21           41            9
 Gherkin (Cucumber)   2731        47530        38901         2687         5942
 GLSL                   98         4646         3135          814          697
 Go                 1066782    471403892    330617093     92141878     48644921
 Go HTML                 3          159          136            0           23
 GraphQL              4140       151337       108919        18476        23942
 Groovy               2540       116575        99027         9093         8455
 Handlebars           3557       107726       101506          884         5336
 Happy                 140       125202       113792            0        11410
 Haskell                 7         1323         1076            0          247
 HCL                 22423      1133226       935622        39852       157752
 HEX                   351       602556       602556            0            0
 HLSL                   67         5749         3861         1173          715
 INI                  1373        33808        20821         6457         6530
 Java                10957      2218181      1600643       378684       238854
 JavaScript         185631     23573870     16909921      4221130      2442819
 JSON                86299     62735340     62713064            0        22276
 JSX                  2070       198841       166560         7756        24525
 Julia                   2          167           94           20           53
 Kotlin               6603       614088       478865        56150        79073
 LLVM                    1            4            4            0            0
 LESS                 2171       300097       224514        32890        42693
 LD Script               1           25           22            2            1
 Liquid                 17          385          326           36           23
 Lisp                    2          188          162            2           24
 LiveScript             22         1922         1229          603           90
 Lua                    44         8433         7010          591          832
 Makefile            11491       499459       342104        58229        99126
 Meson                1392        30830        25108         1749         3973
 Module-Definition     246        28140        24661          960         2519
 MSBuild              1235       144386       138835         4455         1096
 Mustache               47         1482         1409            0           73
 Nix                    27         6959         6303          440          216
 OCaml                  17         5193         4631          320          242
 Objective-C          2562       730881       558934        68499       103448
 Objective-C++         884       188393       141955        15810        30628
 Org                   335         1423         1172           86          165
 Pan                   244        10848         9405          706          737
 Pascal              10520       474753       139258       332037         3458
 Perl                 3101      1440684      1119430       169404       151850
 PHP                 12989      2427725      1485102       667090       275533
 PowerShell            237        20901        14453         3767         2681
 Prolog                134         5443         4782          205          456
 Protocol Buffers    13477      1656421       743696       699680       213045
 Pug                    12          419          399            2           18
 Python              46387     11063007      8814719       812483      1435805
 Q                    2247        58246        45650            0        12596
 QML                     5          270          238            4           28
 R                     265        66448        51294         6096         9058
 RPM Specfile           23         3757         3050          192          515
 Rakefile              663        22464        17887         1275         3302
 Razor                 759        23220        21201          142         1877
 ReStructuredText    12751       452408       334313            0       118095
 Ruby                24054      1666319      1309834       128500       227985
 SRecode Template       28       117961        92823            0        25138
 Sass                 8859       784699       630135        41240       113324
 Scala                1585       270866       169373        66980        34513
 Scheme                 13          975          701          170          104
 Scons                  46         2486         1706          325          455
 Shell               16496      1534577      1237681       150157       146739
 Solidity                2           92           75            0           17
 SQL                  5504      1390412      1232944        78952        78516
 Stylus                  7         3460         2215           28         1217
 SVG                 10126      1302077      1295635         3691         2751
 Swift                3224       660825       472127        89355        99343
 SWIG                    8          114           81           12           21
 TCL                    24         3021         2127          544          350
 TeX                    42        24055        17553         3658         2844
 Plain Text          31070     46754954            0     45988637       766317
 Thrift                 43         9669         4394         3803         1472
 TOML                 4958      1249784      1173696        43886        32202
 TSX                 18879      2311966      2044217        45304       222445
 Twig                    1           67           59            0            8
 TypeScript          35214      3423505      2167573      1010532       245400
 VB6                    43        10337         9431           47          859
 VBScript                4          699          485          145           69
 Vala                   46          466          383            6           77
 Apache Velocity        93         9261         8336           17          908
 Vim script            129        14788        13379          686          723
 Visual Basic            6          678          543           42           93
 Visual Studio Pro|   1601       352905       352679          131           95
 Visual Studio Sol|    894       110886       110234            0          652
 XSL                    68        19321        16298         1409         1614
 XAML                  528       141673       128462         5301         7910
 Xcode Config          387         4860         3660          820          380
 XML                 11390      5791640      5616539        38906       136195
 YAML                20352      4145836      3983010        61088       101738
 Zsh                     4         1759          413         1182          164
-------------------------------------------------------------------------------
 HTML                73218     33249616     32273086       261084       715446
 |- CSS               2457        89410        77582         2963         8865
 |- HTML                 4           64           64            0            0
 |- JavaScript       25732       393948       352151        31589        10208
 (Total)                       33733038     32702883       295636       734519
-------------------------------------------------------------------------------
 Jupyter Notebooks     317            0            0            0            0
 |- Markdown           133         2081           13         1655          413
 |- Python             294        63107        48997         5973         8137
 |- Scala                2           77           57            6           14
 (Total)                          65265        49067         7634         8564
-------------------------------------------------------------------------------
 Markdown            72532      6557110            0      4704055      1853055
 |- ABNF               126          126          126            0            0
 |- Autoconf             1           28           28            0            0
 |- BASH              4445        54455        44444         5290         4721
 |- Batch                2            8            8            0            0
 |- C                   37         2890         2012          517          361
 |- CMake               43          708          490          124           94
 |- C#                   1            6            4            1            1
 |- CoffeeScript         7          255          203           15           37
 |- C++                203        15558        11691         1772         2095
 |- CSS                128         4132         3574           58          500
 |- Dockerfile          29          285          167           81           37
 |- Elixir              22          382          314           44           24
 |- Fish                 1            2            2            0            0
 |- GLSL                 2           18           16            0            2
 |- Go               16866       827254       630340        83515       113399
 |- GraphQL             23          652          580           30           42
 |- Groovy              37          531          502           16           13
 |- Handlebars           4           10           10            0            0
 |- HCL                202         2446         2090           42          314
 |- HTML               410         6383         5632          465          286
 |- INI                382        22244        18887          257         3100
 |- Java                32          719          583           50           86
 |- JavaScript        1724        87020        68001         9379         9640
 |- JSON              2380        64028        61993            0         2035
 |- JSX                237         7407         7046          152          209
 |- Kotlin              22         2449         1750          335          364
 |- Liquid               3          348          337            0           11
 |- Makefile            10           86           51           22           13
 |- Markdown           204         4439            0         3897          542
 |- Meson               58         1165         1039           59           67
 |- Nix                  1            5            4            1            0
 |- Objective-C          9          454          348           72           34
 |- PHP                 15          361          228           89           44
 |- PowerShell          39          250          239            6            5
 |- Python             111         4861         3777          432          652
 |- R                    7          155          105           25           25
 |- Ruby               171         4371         3490          535          346
 |- Rust                 3           21           14            4            3
 |- Scala                4          167          157            0           10
 |- Shell             1272         8110         7119          611          380
 |- SQL                116         1631         1507           51           73
 |- Swift               45         2010         1525          311          174
 |- TOML               374        11944         8743         1655         1546
 |- TSX                 77         6669         5412          429          828
 |- TypeScript          61         2548         1706          539          303
 |- XML                 73         3383         3232           51          100
 |- YAML               547        16731        13621         2280          830
 |- Zsh                  2           25           15            5            5
 (Total)                        7726840       913162      4817272      1996406
-------------------------------------------------------------------------------
 Ruby HTML            4765       292597       269112          779        22706
 |- CSS                 21          199          192            7            0
 |- JavaScript          84         1193          954          176           63
 (Total)                         293989       270258          962        22769
-------------------------------------------------------------------------------
 Rust                  255        88365        70829         5952        11584
 |- Markdown            71         1925            5         1644          276
 (Total)                          90290        70834         7596        11860
-------------------------------------------------------------------------------
 Svelte                  2          142          134            0            8
 |- CSS                  2          104           84            5           15
 |- JavaScript           2          147          122            0           25
 (Total)                            393          340            5           48
-------------------------------------------------------------------------------
 Vue                   313         8839         7926          110          803
 |- CSS                 77         2026         1828           17          181
 |- HTML               285        16496        15054          428         1014
 |- JavaScript         308        26726        24721          936         1069
 |- Pug                 24          562          557            0            5
 |- Stylus              22          711          571            5          135
 (Total)                          55360        50657         1496         3207
===============================================================================
 Total              2184290    766307432    532527386    165694121     68085925
===============================================================================
```

### PR DESCRIPTION
**Pull request by adam-tokarski**
Fixes #891 

#### Provided changes:
* the `Files` column is widened by 2 chars (in origin issue it was suggested 1 would be enough though, but 2 seems like nicely fitting as well)
* some consts are provided to store these columns width magic numbers to ease work a little bit
* .gitignore was adjusted - I've regenerated it using https://www.toptal.com/developers/gitignore/ and provided back some already existing ones. Some, like `.commit_message` or `node_modules`, were removed as seems like some leftovers. Also, `.idea` is added for cases of usage Jetbrains tools.

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Thank you for your PR! However it seems that the files output is currently misaligned. Would you be able to address that?

Screenshot 2022-08-15 at 08 51 28

**Comment by adam-tokarski** [comment]
Will do but not earlier than in 2 weeks as I'm off now. Thanks for catching that issue!

**Comment by adam-tokarski** [comment]
> Thank you for your PR! However it seems that the files output is currently misaligned. Would you be able to address that?

This is interesting. I've checked that and it looks like that for me
image

Could you, please, provide full statement how you generate the output that you can see misaligned rows?

**Comment by adam-tokarski** [comment]
Right. Apparently I've been checking that using wrong version of `tokei`, my bad. 

There is updated version - please especially check whether I handled properly moving these consts to dedicated file. @XAMPPRocky

**Comment by adam-tokarski** [comment]
@XAMPPRocky I'm pinging you, just in case you have missed my last changes. Also, I guess you're very busy, so do not want to disturb you.

**Comment by adam-tokarski** [comment]
@XAMPPRocky ping :smiley_cat:

**Comment by Sigmanificient** [comment]
Still waiting on that one :sweat_smile:

**Comment by XAMPPRocky** [comment]
Thank you for your PR!

**Comment by adam-tokarski** [comment]
@XAMPPRocky 
Hmm, it seems that this is failing on release-plz action with 
> ERROR  Cargo.lock is present in your .gitignore and is also committed. Remove it from your repository or from your `.gitignore` file.

Should we preserve `Cargo.lock` here? If so, I would need to remove that from `.gitignore` as it's suggested.

**Comment by XAMPPRocky** [comment]
> Should we preserve Cargo.lock here? If so, I would need to remove that from .gitignore as it's suggested.

Yes Cargo.lock should be committed as this is a binary crate.

**Comment by adam-tokarski** [comment]
> Yes Cargo.lock should be committed as this is a binary crate.

So there is #1115 to handle that.

**Pull request merged**
