### PR TITLE
Add Phix

### PR DESCRIPTION
**Pull request by petelomax**

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Thank you for your PR! Can you rebase this on top of main, it seems like CI did not run.

**Comment by petelomax** [comment]
Sorry, not quite sure what "rebase" means... I'm a "GitHub Desktop" user, I've done a quick "sync fork", dunno if that will help.

**Comment by XAMPPRocky** [comment]
With the terminal, from your branch run `git rebase origin/master`

**Comment by petelomax** [comment]
Got it to say "Current branch master is up to date."....

**Comment by petelomax** [comment]
bump

**Comment by XAMPPRocky** [comment]
I'd recommend just scrapping the current, using a new main branch, apply your changes there, and force push to this branch.

**Pull request closed without merging**
