### PR TITLE
add OpenPolicyAgent support and test

### PR DESCRIPTION
**Pull request by eulegang**
Not quite sure if I need an issue before adding support but it'd be awesome to have some support for the Open Policy Agent

### CODE REVIEW

**Comment by eulegang** [comment]
Am I missing how to contribute here?

**Comment by XAMPPRocky** [comment]
Thank you for your PR! Sorry, I've been busy with other projects at the moment, and will review this soon.

**Comment by eulegang** [comment]
Gotcha, thanks for the fast reply.

**Comment by XAMPPRocky** [comment]
Thank you for your PR!

**Pull request merged**
