### PR TITLE
Add support for the Factor language.

### PR DESCRIPTION
**Pull request by mrjbq7**
Hi,

Adding support for the Factor language.

https://github.com/factor/factor

https://factorcode.org

### CODE REVIEW

**Comment by mrjbq7** [comment]
What's the best way to help get this into an upcoming release?

**Comment by XAMPPRocky** [comment]
Thank you for your PR! Sorry for the late reply, I'm focused on other projects, I maintain this project entirely in my spare time, so there's no schedule for a new release. I will review and merge this before I make a new release though.

**Comment by XAMPPRocky** [comment]
Thank you for your PR, and congrats on your first contribution! 🎉

**Comment by mrjbq7** [comment]
Yay! Thanks!

I love using tokei! Great work!

**Pull request merged**
