### PR TITLE
Added Rusty Object Notation

### LINKED ISSUE #394: Count *.ron files as well
There is this (subjectively awesome) format called [`*.ron`](https://github.com/ron-rs/ron) - I was surprised seeing that not being counted yet.

So I'd propose a feature request: Count `*.ron` files as well, including separation of comment- and empty lines.

### PR DESCRIPTION
**Pull request by fkarg**
fixes #394

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
@fkarg Thank you for your issue! Could you also add a test file similar to [`tests/data/rust.rs`](../blob/master/tests/data/rust.rs) in the data folder? You can read more about adding this file in the [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md#tests). Once that done and it passes one of the CI platforms, I would be happy to merge it in.

**Comment by fkarg** [comment]
travis errors due to the cache being too big (requiring too long to load) - here you go

**Comment by XAMPPRocky** [comment]
@fkarg You need to provide a comment at the top of the file that says what the stats are.

**Comment by fkarg** [comment]
Ah I see. Should work now

**Comment by XAMPPRocky** [comment]
Thank you again for your PR and congrats on your first contribution! 🎉

**Pull request merged**
