### PR TITLE
Fix memmap audit warning

### LINKED ISSUE #782: RUSTSEC-2020-0077: memmap is unmaintained
> memmap is unmaintained

| Details             |                                                |
| ------------------- | ---------------------------------------------- |
| Status              | unmaintained                |
| Package             | `memmap`                      |
| Version             | `0.7.0`                   |
| URL                 | [https://github.com/danburkert/memmap-rs/issues/90](https://github.com/danburkert/memmap-rs/issues/90) |
| Date                | 2020-12-02                         |

The author of the `memmap` crate is unresponsive.

Maintained alternatives:

- [`mapr`](https://github.com/filecoin-project/mapr)
- [`memmap2`](https://github.com/RazrFalcon/memmap2-rs)

See [advisory page](https://rustsec.org/advisories/RUSTSEC-2020-0077.html) for additional details.

### PR DESCRIPTION
**Pull request by brightly-salty**
Fixes #782 by updating `grep-searcher` from `0.1.7` to `0.1.8`

### CODE REVIEW

**Comment by brightly-salty** [comment]
Looks like the CI fails because of compilation errors with `git2`. Let me know if you want me to fix these before this is merged

**Comment by XAMPPRocky** [comment]
> Looks like the CI fails because of compilation errors with git2. Let me know if you want me to fix these before this is merged

Thank you for your PR! If you could make a separate PR to fix `git2` I would appreciate it.

**Comment by brightly-salty** [comment]
> > Looks like the CI fails because of compilation errors with git2. Let me know if you want me to fix these before this is merged
> 
> Thank you for your PR! If you could make a separate PR to fix `git2` I would appreciate it.

I've done so at #793 . If you would review and merge that PR, I can rebase this branch so the tests will work again.

**Comment by XAMPPRocky** [comment]
Thank you for your PR!

**Pull request merged**
