### PR TITLE
Add LOLCODE support

### PR DESCRIPTION
**Pull request by MonliH**
This PR adds [LOLCODE](http://www.lolcode.org/) language support to tokei. 

Yes, I really need this, as I'm working on a project involving this ~~horrid~~ awesome language :-)

### CODE REVIEW

**Comment by MonliH** [comment]
Hmmm, seems like the test failed because of a fluke while installing rust:
> info: installing component 'rustc'
> memory allocation of 16777216 bytes failed

I added an empty commit to rerun(?) the CI.

**Comment by MonliH** [comment]
Hmm, what's going on with the CI being cancelled? I can't seem to view the logs, so it doesn't seem like it's failed.

**Comment by XAMPPRocky** [comment]
I'm not sure, GitHub Actions can be quite buggy at times, especially for a project that uses it as extensively as this. I've restarted the jobs.

**Comment by XAMPPRocky** [comment]
Thank you for your PR, and congrats on your first contribution! 🎉

**Pull request merged**
