### PR TITLE
Add support for Velocity and Dust

### PR DESCRIPTION
**Pull request by isker**

### CODE REVIEW

**Comment by isker** [comment]
Sorry, I'm missing some steps from CONTRIBUTING.md.  Let me fix that up.

**Comment by isker** [comment]
There we go.

**Comment by XAMPPRocky** [comment]
@isker Thank you for your PR! I just made some changes to the CI could you rebase your changes and then I would be happy to merge this!

**Comment by isker** [comment]
Close enough?

**Comment by XAMPPRocky** [comment]
@isker Yes, the appveyor check shouldn't be there. Thank you again for your PR and congrats on your first contribution! 🎉

**Pull request merged**
