### PR TITLE
added wgsl + metal shading languages

### PR DESCRIPTION
**Pull request by adamnemecek**

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Thank you for your PR! Would you also be able to add test files for each of the languages? Once that is in I would be happy to merge this in.

**Comment by adamnemecek** [comment]
Ok done.

**Comment by adamnemecek** [comment]
Good to go?

**Comment by XAMPPRocky** [comment]
Yes, I'm going to merge this soon, I want to go through and merge other PRs that have bee waiting too at the same time so I just need to find the time and then I'll merge this.

**Comment by adamnemecek** [comment]
Ok take your time.

**Comment by XAMPPRocky** [comment]
Thank you for your PR, and congrats on your first contribution! 🎉

**Pull request merged**
