### PR TITLE
Fix backslash bug (#915)

### PR DESCRIPTION
**Pull request by sceneq**

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Thank you for your PR! You also need add the check for is_verbatim, as escapes don't work on those strings. Also can you add the original example from the issue as a test.

**Comment by sceneq** [comment]
Where should I add the test?
This problem(#915) is not limited to java, but also occurs in python code such as
```python
"\\" # 1
# com1
# com2
"\\" # 2
# com3
# com4
# com5
```

**Comment by XAMPPRocky** [comment]
> Where should I add the test?

You can update the Java, or Python test. We don’t need to check it in every language, we just need at least one of them testing it.

**Comment by sceneq** [comment]
Fixed the condition and updated the java test

**Comment by XAMPPRocky** [comment]
Thank you for your PR, and congrats on your first contribution! 🎉

**Pull request merged**
