### PR TITLE
update readme: add tokei-pie in related tools.

### PR DESCRIPTION
**Pull request by laixintao**
Hi, I wrote a small tool that can parse `tokei -o json`, use like this `tokei -o json | tokei-pie` then generate a sunburst chart, displaying it by opening a tab in the browser. It is interactive, you can click around the sectors to see the code lines reactively.

It parses `tokei`'s json output so this feature do not touch tokei's code at all.

I think it is handy working with tokei. So I think it may interest other tokei users, so I open this PR.

I know it may be rude for opening a PR to just promote myself's project like this, I totally understand if you don't want to accept this, you can just close it if so. :D

https://github.com/laixintao/tokei-pie

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Thank you for your PR! This looks super cool, I can't wait to show it to other people. 😄

**Comment by laixintao** [comment]
Thanks! it means a lot to me. Let me know if you have more ideas or feedbacks on this tool. :)

**Comment by XAMPPRocky** [comment]
@laixintao The couple of things that I noticed, just trying it out.

- I initially foolishly ran `tokei | tokei-pie`, and I get a `JSONDecodeError` backtrace. It would be nice if the error was caught, and it printed a more informative error message like "Non valid JSON input, maybe missing `-o json` flag", or something like.
- I noticed it opens up a webserver to serve the result. It would be nice if I could output it to a file somewhere instead, and use `open`.

**Comment by laixintao** [comment]
Thanks! Excellent advice.

1. json decode error will not print an error message then exist as code=128
2. you can now use `tokei -o json | tokei-pie -o a.html` to write chart to a *single* HTML file, copy it around or open it anytime, won't open browser when `-o` used.


image

**Pull request merged**
