### PR TITLE
Support home directory in from_config_files

### PR DESCRIPTION
**Pull request by kobataiwan**
Support home directory in from_config_files

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Thank you for your PR! Would you also be able to update the documentation to include this new location? Once that's done and everything passes I would be happy to merge this in.

**Comment by kobataiwan** [comment]
> Thank you for your PR! Would you also be able to update the documentation to include this new location? Once that's done and everything passes I would be happy to merge this in.

sure

**Comment by kobataiwan** [comment]
Update README.md for configuraiton of Tokei.
But I only update the linux related part.

**Comment by XAMPPRocky** [comment]
Thank you for the documentation, but I actually meant the API documentation on line 55 of `src/config.rs`, sorry for not being clear.

**Comment by kobataiwan** [comment]
> Thank you for the documentation, but I actually meant the API documentation on line 55 of `src/config.rs`, sorry for not being clear.

Thanks for notification and have updated the documentation.

**Comment by XAMPPRocky** [comment]
Thank you for your PR, and congrats on your first contribution! 🎉

**Pull request merged**
